# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  generate-schema-to-rust:
    cmds:
      - >
        pnpm exec quicktype
        --top-level AwsRegionalProductServices
        --src-lang schema
        --lang rust
        --visibility public
        --derive-clone
        --derive-debug
        --derive-partial-eq
        --out src/aws_regional_product_services/schema.rs
        schema/aws-regional-product-services.json
  release.patch:
    cmds:
      - cargo release patch
  release.patch.exec:
    cmds:
      - cargo release patch --execute
